package com.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoctorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllPropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllUpdatablePropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorUpdatableFieldsEquals(expected, actual);
        assertDoctorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAutoGeneratedPropertiesEquals(Doctor expected, Doctor actual) {
        assertThat(actual)
            .as("Verify Doctor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableFieldsEquals(Doctor expected, Doctor actual) {
        assertThat(actual)
            .as("Verify Doctor relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getSpecialization()).as("check specialization").isEqualTo(expected.getSpecialization()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableRelationshipsEquals(Doctor expected, Doctor actual) {
        // empty method
    }
}
