package com.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TreatmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTreatmentAllPropertiesEquals(Treatment expected, Treatment actual) {
        assertTreatmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTreatmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTreatmentAllUpdatablePropertiesEquals(Treatment expected, Treatment actual) {
        assertTreatmentUpdatableFieldsEquals(expected, actual);
        assertTreatmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTreatmentAutoGeneratedPropertiesEquals(Treatment expected, Treatment actual) {
        assertThat(actual)
            .as("Verify Treatment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTreatmentUpdatableFieldsEquals(Treatment expected, Treatment actual) {
        assertThat(actual)
            .as("Verify Treatment relevant properties")
            .satisfies(a ->
                assertThat(a.getTreatmentDescription()).as("check treatmentDescription").isEqualTo(expected.getTreatmentDescription())
            )
            .satisfies(a -> assertThat(a.getTreatmentDate()).as("check treatmentDate").isEqualTo(expected.getTreatmentDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTreatmentUpdatableRelationshipsEquals(Treatment expected, Treatment actual) {
        assertThat(actual)
            .as("Verify Treatment relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()))
            .satisfies(a -> assertThat(a.getDoctor()).as("check doctor").isEqualTo(expected.getDoctor()))
            .satisfies(a -> assertThat(a.getDisease()).as("check disease").isEqualTo(expected.getDisease()));
    }
}
